apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-boost3
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: thehijabicoder/nginx_server_boost3.0:img1
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-boost3-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 35000
      targetPort: 35000
      nodePort: 35000
