apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-3
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image:
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-b3-nodeport
  namespace: sathwikakancherla
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 35000
      targetPort: 8080
      nodePort: 35000
